### ISSUE TITLE
polity_ccode gone?

### ISSUE THREAD

**Issue by saschariaz** [xmarquez/QuickUDS#1]
Hi,

there used to be a polity_ccode identifier variable in previous versions of the extended_uds dataset, correct? It's not available anymore in the current version? Is there any way to retrieve it?

**Comment by xmarquez** [comment]
Hi saschariaz - yes it's gone from the current build. It may take me a few days to redo it, but if you need a way to quickly merge this data with polity, use my package democracyData (https://xmarquez.github.io/democracyData/) - it gives you access to the polity dataset with GWn/COW codes, and the function country_year_coder also lets you find the polity codes for the country years in question.

**Comment by xmarquez** [comment]
Hi saschariaz - I've put back `polity_ccode` in the `extended_uds` dataset. (I've also recalculated it with the new BMR 3.0 and EIU releases).
